const express = require("express");
const router = express.Router();

const { Document, Packer, Paragraph, HeadingLevel, TextRun } = require("docx");
const ExcelJS = require("exceljs");
const PptxGenJS = require("pptxgenjs");
const archiver = require("archiver");

const MAX_CONTENT_CHARS = 20000;

// Strips the light markdown the tutor's answers use (**bold**, *italic*,
// `code`, and heading #'s) down to plain text, since Word/Excel/PPT don't
// render markdown syntax on their own.
function stripMd(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/^#{1,6}\s+/, "")
    .trim();
}

// Turns the raw answer text into a flat list of typed lines (heading /
// bullet / paragraph) that each export format can lay out in its own way.
function parseContentBlocks(raw) {
  const lines = (raw || "").split("\n");
  const blocks = [];
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;
    if (/^#{1,6}\s+/.test(line)) {
      blocks.push({ type: "heading", text: stripMd(line) });
    } else if (/^[-*]\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^[-*]\s+/, "")) });
    } else if (/^\d+\.\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^\d+\.\s+/, "")) });
    } else {
      blocks.push({ type: "para", text: stripMd(line) });
    }
  }
  if (!blocks.length) blocks.push({ type: "para", text: "(No content)" });
  return blocks;
}

async function buildDocxBuffer(title, blocks) {
  const children = [new Paragraph({ text: title, heading: HeadingLevel.TITLE })];
  blocks.forEach(b => {
    if (b.type === "heading") {
      children.push(new Paragraph({ text: b.text, heading: HeadingLevel.HEADING_1, spacing: { before: 200 } }));
    } else if (b.type === "bullet") {
      children.push(new Paragraph({ text: b.text, bullet: { level: 0 } }));
    } else {
      children.push(new Paragraph({ children: [new TextRun(b.text)], spacing: { after: 120 } }));
    }
  });
  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}

async function buildXlsxBuffer(title, blocks) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet((title || "Notes").slice(0, 28) || "Notes");
  ws.columns = [
    { header: "#", key: "idx", width: 6 },
    { header: "Type", key: "type", width: 12 },
    { header: "Content", key: "text", width: 100 }
  ];
  ws.getRow(1).font = { bold: true };
  blocks.forEach((b, i) => {
    const row = ws.addRow({ idx: i + 1, type: b.type, text: b.text });
    row.alignment = { wrapText: true, vertical: "top" };
    if (b.type === "heading") row.font = { bold: true };
  });
  return wb.xlsx.writeBuffer();
}

async function buildPptxBuffer(title, blocks) {
  const pptx = new PptxGenJS();

  const titleSlide = pptx.addSlide();
  titleSlide.addText(title, { x: 0.5, y: 2.1, w: 9, h: 1.3, fontSize: 32, bold: true, align: "center" });
  titleSlide.addText("Generated by StudyMate AI", { x: 0.5, y: 3.4, w: 9, h: 0.5, fontSize: 13, align: "center", color: "888888" });

  const MAX_LINES_PER_SLIDE = 6;
  let slide = null;
  let lineCount = 0;

  function startSlide(headingText) {
    slide = pptx.addSlide();
    slide.addText(headingText || title, { x: 0.4, y: 0.35, w: 9.2, h: 0.7, fontSize: 24, bold: true });
    lineCount = 0;
  }

  blocks.forEach(b => {
    if (b.type === "heading") {
      startSlide(b.text);
      return;
    }
    if (!slide || lineCount >= MAX_LINES_PER_SLIDE) startSlide();
    slide.addText(b.text, {
      x: 0.6, y: 1.15 + lineCount * 0.78, w: 8.8, h: 0.72,
      fontSize: 16, bullet: b.type === "bullet", valign: "top"
    });
    lineCount++;
  });

  return pptx.write("nodebuffer");
}

router.post("/export", async (req, res) => {
  try {
    const format = (req.body?.format || "").toString().toLowerCase();
    const rawTitle = (req.body?.title || "StudyMate Notes").toString().slice(0, 100).trim();
    const title = rawTitle || "StudyMate Notes";
    const content = (req.body?.content || "").toString();

    if (!content.trim()) {
      return res.status(400).json({ error: "There's nothing to export yet." });
    }
    if (content.length > MAX_CONTENT_CHARS) {
      return res.status(400).json({ error: "That's too long to export in one file." });
    }
    if (!["docx", "xlsx", "pptx", "zip"].includes(format)) {
      return res.status(400).json({ error: "Unknown export format." });
    }

    const blocks = parseContentBlocks(content);
    const safeFileName = title.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, "_").slice(0, 60) || "StudyMate_Notes";

    if (format === "docx") {
      const buf = await buildDocxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.docx"`);
      return res.send(buf);
    }

    if (format === "xlsx") {
      const buf = await buildXlsxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.xlsx"`);
      return res.send(buf);
    }

    if (format === "pptx") {
      const buf = await buildPptxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.pptx"`);
      return res.send(buf);
    }

    // format === "zip" — bundle all three into one download
    const [docxBuf, xlsxBuf, pptxBuf] = await Promise.all([
      buildDocxBuffer(title, blocks),
      buildXlsxBuffer(title, blocks),
      buildPptxBuffer(title, blocks)
    ]);

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.zip"`);

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", err => {
      console.error("Zip archive error:", err);
      if (!res.headersSent) res.status(500);
      res.end();
    });
    archive.pipe(res);
    archive.append(docxBuf, { name: `${safeFileName}.docx` });
    archive.append(xlsxBuf, { name: `${safeFileName}.xlsx` });
    archive.append(pptxBuf, { name: `${safeFileName}.pptx` });
    await archive.finalize();

  } catch (err) {
    console.error("Export route error:", err);
    if (!res.headersSent) {
      res.status(500).json({ error: "Couldn't generate that file." });
    } else {
      res.end();
    }
  }
});

module.exports = router;
const express = require("express");
const router = express.Router();

const { Document, Packer, Paragraph, HeadingLevel, TextRun } = require("docx");
const ExcelJS = require("exceljs");
const PptxGenJS = require("pptxgenjs");
const archiver = require("archiver");

const MAX_CONTENT_CHARS = 20000;

// Strips the light markdown the tutor's answers use (**bold**, *italic*,
// `code`, and heading #'s) down to plain text, since Word/Excel/PPT don't
// render markdown syntax on their own.
function stripMd(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/^#{1,6}\s+/, "")
    .trim();
}

// Turns the raw answer text into a flat list of typed lines (heading /
// bullet / paragraph) that each export format can lay out in its own way.
function parseContentBlocks(raw) {
  const lines = (raw || "").split("\n");
  const blocks = [];
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;
    if (/^#{1,6}\s+/.test(line)) {
      blocks.push({ type: "heading", text: stripMd(line) });
    } else if (/^[-*]\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^[-*]\s+/, "")) });
    } else if (/^\d+\.\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^\d+\.\s+/, "")) });
    } else {
      blocks.push({ type: "para", text: stripMd(line) });
    }
  }
  if (!blocks.length) blocks.push({ type: "para", text: "(No content)" });
  return blocks;
}

async function buildDocxBuffer(title, blocks) {
  const children = [new Paragraph({ text: title, heading: HeadingLevel.TITLE })];
  blocks.forEach(b => {
    if (b.type === "heading") {
      children.push(new Paragraph({ text: b.text, heading: HeadingLevel.HEADING_1, spacing: { before: 200 } }));
    } else if (b.type === "bullet") {
      children.push(new Paragraph({ text: b.text, bullet: { level: 0 } }));
    } else {
      children.push(new Paragraph({ children: [new TextRun(b.text)], spacing: { after: 120 } }));
    }
  });
  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}

async function buildXlsxBuffer(title, blocks) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet((title || "Notes").slice(0, 28) || "Notes");
  ws.columns = [
    { header: "#", key: "idx", width: 6 },
    { header: "Type", key: "type", width: 12 },
    { header: "Content", key: "text", width: 100 }
  ];
  ws.getRow(1).font = { bold: true };
  blocks.forEach((b, i) => {
    const row = ws.addRow({ idx: i + 1, type: b.type, text: b.text });
    row.alignment = { wrapText: true, vertical: "top" };
    if (b.type === "heading") row.font = { bold: true };
  });
  return wb.xlsx.writeBuffer();
}

async function buildPptxBuffer(title, blocks) {
  const pptx = new PptxGenJS();

  const titleSlide = pptx.addSlide();
  titleSlide.addText(title, { x: 0.5, y: 2.1, w: 9, h: 1.3, fontSize: 32, bold: true, align: "center" });
  titleSlide.addText("Generated by StudyMate AI", { x: 0.5, y: 3.4, w: 9, h: 0.5, fontSize: 13, align: "center", color: "888888" });

  const MAX_LINES_PER_SLIDE = 6;
  let slide = null;
  let lineCount = 0;

  function startSlide(headingText) {
    slide = pptx.addSlide();
    slide.addText(headingText || title, { x: 0.4, y: 0.35, w: 9.2, h: 0.7, fontSize: 24, bold: true });
    lineCount = 0;
  }

  blocks.forEach(b => {
    if (b.type === "heading") {
      startSlide(b.text);
      return;
    }
    if (!slide || lineCount >= MAX_LINES_PER_SLIDE) startSlide();
    slide.addText(b.text, {
      x: 0.6, y: 1.15 + lineCount * 0.78, w: 8.8, h: 0.72,
      fontSize: 16, bullet: b.type === "bullet", valign: "top"
    });
    lineCount++;
  });

  return pptx.write("nodebuffer");
}

router.post("/export", async (req, res) => {
  try {
    const format = (req.body?.format || "").toString().toLowerCase();
    const rawTitle = (req.body?.title || "StudyMate Notes").toString().slice(0, 100).trim();
    const title = rawTitle || "StudyMate Notes";
    const content = (req.body?.content || "").toString();

    if (!content.trim()) {
      return res.status(400).json({ error: "There's nothing to export yet." });
    }
    if (content.length > MAX_CONTENT_CHARS) {
      return res.status(400).json({ error: "That's too long to export in one file." });
    }
    if (!["docx", "xlsx", "pptx", "zip"].includes(format)) {
      return res.status(400).json({ error: "Unknown export format." });
    }

    const blocks = parseContentBlocks(content);
    const safeFileName = title.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, "_").slice(0, 60) || "StudyMate_Notes";

    if (format === "docx") {
      const buf = await buildDocxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.docx"`);
      return res.send(buf);
    }

    if (format === "xlsx") {
      const buf = await buildXlsxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.xlsx"`);
      return res.send(buf);
    }

    if (format === "pptx") {
      const buf = await buildPptxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.pptx"`);
      return res.send(buf);
    }

    // format === "zip" — bundle all three into one download
    const [docxBuf, xlsxBuf, pptxBuf] = await Promise.all([
      buildDocxBuffer(title, blocks),
      buildXlsxBuffer(title, blocks),
      buildPptxBuffer(title, blocks)
    ]);

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.zip"`);

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", err => {
      console.error("Zip archive error:", err);
      if (!res.headersSent) res.status(500);
      res.end();
    });
    archive.pipe(res);
    archive.append(docxBuf, { name: `${safeFileName}.docx` });
    archive.append(xlsxBuf, { name: `${safeFileName}.xlsx` });
    archive.append(pptxBuf, { name: `${safeFileName}.pptx` });
    await archive.finalize();

  } catch (err) {
    console.error("Export route error:", err);
    if (!res.headersSent) {
      res.status(500).json({ error: "Couldn't generate that file." });
    } else {
      res.end();
    }
  }
});

module.exports = router;
const express = require("express");
const router = express.Router();

const { Document, Packer, Paragraph, HeadingLevel, TextRun } = require("docx");
const ExcelJS = require("exceljs");
const PptxGenJS = require("pptxgenjs");
const archiver = require("archiver");

const MAX_CONTENT_CHARS = 20000;

// Strips the light markdown the tutor's answers use (**bold**, *italic*,
// `code`, and heading #'s) down to plain text, since Word/Excel/PPT don't
// render markdown syntax on their own.
function stripMd(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/^#{1,6}\s+/, "")
    .trim();
}

// Turns the raw answer text into a flat list of typed lines (heading /
// bullet / paragraph) that each export format can lay out in its own way.
function parseContentBlocks(raw) {
  const lines = (raw || "").split("\n");
  const blocks = [];
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;
    if (/^#{1,6}\s+/.test(line)) {
      blocks.push({ type: "heading", text: stripMd(line) });
    } else if (/^[-*]\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^[-*]\s+/, "")) });
    } else if (/^\d+\.\s+/.test(line)) {
      blocks.push({ type: "bullet", text: stripMd(line.replace(/^\d+\.\s+/, "")) });
    } else {
      blocks.push({ type: "para", text: stripMd(line) });
    }
  }
  if (!blocks.length) blocks.push({ type: "para", text: "(No content)" });
  return blocks;
}

async function buildDocxBuffer(title, blocks) {
  const children = [new Paragraph({ text: title, heading: HeadingLevel.TITLE })];
  blocks.forEach(b => {
    if (b.type === "heading") {
      children.push(new Paragraph({ text: b.text, heading: HeadingLevel.HEADING_1, spacing: { before: 200 } }));
    } else if (b.type === "bullet") {
      children.push(new Paragraph({ text: b.text, bullet: { level: 0 } }));
    } else {
      children.push(new Paragraph({ children: [new TextRun(b.text)], spacing: { after: 120 } }));
    }
  });
  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}

async function buildXlsxBuffer(title, blocks) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet((title || "Notes").slice(0, 28) || "Notes");
  ws.columns = [
    { header: "#", key: "idx", width: 6 },
    { header: "Type", key: "type", width: 12 },
    { header: "Content", key: "text", width: 100 }
  ];
  ws.getRow(1).font = { bold: true };
  blocks.forEach((b, i) => {
    const row = ws.addRow({ idx: i + 1, type: b.type, text: b.text });
    row.alignment = { wrapText: true, vertical: "top" };
    if (b.type === "heading") row.font = { bold: true };
  });
  return wb.xlsx.writeBuffer();
}

async function buildPptxBuffer(title, blocks) {
  const pptx = new PptxGenJS();

  const titleSlide = pptx.addSlide();
  titleSlide.addText(title, { x: 0.5, y: 2.1, w: 9, h: 1.3, fontSize: 32, bold: true, align: "center" });
  titleSlide.addText("Generated by StudyMate AI", { x: 0.5, y: 3.4, w: 9, h: 0.5, fontSize: 13, align: "center", color: "888888" });

  const MAX_LINES_PER_SLIDE = 6;
  let slide = null;
  let lineCount = 0;

  function startSlide(headingText) {
    slide = pptx.addSlide();
    slide.addText(headingText || title, { x: 0.4, y: 0.35, w: 9.2, h: 0.7, fontSize: 24, bold: true });
    lineCount = 0;
  }

  blocks.forEach(b => {
    if (b.type === "heading") {
      startSlide(b.text);
      return;
    }
    if (!slide || lineCount >= MAX_LINES_PER_SLIDE) startSlide();
    slide.addText(b.text, {
      x: 0.6, y: 1.15 + lineCount * 0.78, w: 8.8, h: 0.72,
      fontSize: 16, bullet: b.type === "bullet", valign: "top"
    });
    lineCount++;
  });

  return pptx.write("nodebuffer");
}

router.post("/export", async (req, res) => {
  try {
    const format = (req.body?.format || "").toString().toLowerCase();
    const rawTitle = (req.body?.title || "StudyMate Notes").toString().slice(0, 100).trim();
    const title = rawTitle || "StudyMate Notes";
    const content = (req.body?.content || "").toString();

    if (!content.trim()) {
      return res.status(400).json({ error: "There's nothing to export yet." });
    }
    if (content.length > MAX_CONTENT_CHARS) {
      return res.status(400).json({ error: "That's too long to export in one file." });
    }
    if (!["docx", "xlsx", "pptx", "zip"].includes(format)) {
      return res.status(400).json({ error: "Unknown export format." });
    }

    const blocks = parseContentBlocks(content);
    const safeFileName = title.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, "_").slice(0, 60) || "StudyMate_Notes";

    if (format === "docx") {
      const buf = await buildDocxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.docx"`);
      return res.send(buf);
    }

    if (format === "xlsx") {
      const buf = await buildXlsxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.xlsx"`);
      return res.send(buf);
    }

    if (format === "pptx") {
      const buf = await buildPptxBuffer(title, blocks);
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
      res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.pptx"`);
      return res.send(buf);
    }

    // format === "zip" — bundle all three into one download
    const [docxBuf, xlsxBuf, pptxBuf] = await Promise.all([
      buildDocxBuffer(title, blocks),
      buildXlsxBuffer(title, blocks),
      buildPptxBuffer(title, blocks)
    ]);

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${safeFileName}.zip"`);

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", err => {
      console.error("Zip archive error:", err);
      if (!res.headersSent) res.status(500);
      res.end();
    });
    archive.pipe(res);
    archive.append(docxBuf, { name: `${safeFileName}.docx` });
    archive.append(xlsxBuf, { name: `${safeFileName}.xlsx` });
    archive.append(pptxBuf, { name: `${safeFileName}.pptx` });
    await archive.finalize();

  } catch (err) {
    console.error("Export route error:", err);
    if (!res.headersSent) {
      res.status(500).json({ error: "Couldn't generate that file." });
    } else {
      res.end();
    }
  }
});

module.exports = router;
